### PR TITLE
Skios 150 feed adding page

### PR DESCRIPTION
**Pull request by jeppard**
# Skiosa - PR
- [x] added test(s), or explain why one is not needed/possible...
- [x] added comments to all the functions
- [x] added documentation to latex project
- [x] code can't be split up into smaller logical units
- [x] code is formated and linted

### CODE REVIEW

**Comment by simonmorgenstern** [comment]
fix tests 😘

**Comment by jeppard** [comment]
Fixed Tests

**Review by simonmorgenstern — COMMENTED** [review]
- [x] remove click anywhere to close behaviour

- [x] insert close button like specified in mockup (does not need to look like in mockup, it just has to match the design theme)

- [x] please add a little **vertical** padding to text input labels :)

**Comment by jeppard** [comment]
Done requested changes

**Review by simonmorgenstern — APPROVED** [review]
🦆 👍🏼

**Pull request merged**
