### PR TITLE
SKIOS 80 Added clip board to share

### PR DESCRIPTION
**Pull request by grossamos**
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ
PRAKHKJAHDKJAHDKJHSAKJDHQKJHDKJHDKJAHkJAHKAJ

### CODE REVIEW

**Comment by simonmorgenstern** [comment]
fix tests 😘

**Comment by grossamos** [comment]
It's not possible to test this line

**Comment by simonmorgenstern** [comment]
at least add js doc to your complex function 😉 
will be merged if thats the case :)

**Review by simonmorgenstern — APPROVED** [review]
👀 ❌  lol

**Comment by grossamos** [comment]
Added docs, @LukasLJL, could you merge this (I added a single line of actual javascript code, which I don't know how to test)

**Pull request merged**
